import { index, layout, type RouteConfig, route } from "@react-router/dev/routes";

const visualRoutes =
  process.env.VISUAL_TESTING === "true"
    ? [
        route("__visual/public-shell", "routes/__visual.public-shell.tsx"),
        route("__visual/home", "routes/__visual.home.tsx"),
        route("__visual/search", "routes/__visual.search.tsx"),
        route("__visual/car", "routes/__visual.car.tsx"),
        route("__visual/bookings", "routes/__visual.bookings.tsx"),
        route("__visual/booking", "routes/__visual.booking.tsx"),
        route("__visual/booking-cancel", "routes/__visual.booking-cancel.tsx"),
        route("__visual/booking-modify", "routes/__visual.booking-modify.tsx"),
        route("__visual/booking-extend", "routes/__visual.booking-extend.tsx"),
        route("__visual/profile", "routes/__visual.profile.tsx"),
        route("__visual/referrals", "routes/__visual.referrals.tsx"),
        route("__visual/user-nav", "routes/__visual.user-nav.tsx"),
      ]
    : [];

export default [
  route("api/places/autocomplete", "routes/api.places.autocomplete.ts"),
  route("api/places/resolve", "routes/api.places.resolve.ts"),
  route("api/search-flight", "routes/api.search-flight.ts"),
  route("api/calculate-trip-duration", "routes/api.calculate-trip-duration.ts"),
  route("api/booking-pricing-preview", "routes/api.booking-pricing-preview.ts"),
  route("api/ai-search", "routes/api.ai-search.ts"),
  route("api/account/delete", "routes/api.account.delete.ts"),
  route("robots.txt", "routes/robots.txt.ts"),
  route("sitemap.xml", "routes/sitemap.xml.ts"),
  layout("routes/_public.tsx", [
    index("routes/home.tsx"),
    route("search", "routes/search.tsx"),
    route("cars/:carSlug", "routes/cars.$carSlug.tsx"),
    route("bookings/payment-status", "routes/payment-status.tsx"),
    route("about", "routes/about.tsx"),
    route("faq", "routes/faq.tsx"),
    route("terms", "routes/terms.tsx"),
    route("privacy", "routes/privacy.tsx"),
    route("cookies", "routes/cookies.tsx"),
    route("bookings", "routes/bookings.tsx"),
    route("bookings/lookup", "routes/bookings.lookup.tsx"),
    route("bookings/guest", "routes/bookings.guest.ts"),
    route("bookings/:bookingId", "routes/bookings.$bookingId.tsx"),
    route("bookings/:bookingId/extend", "routes/bookings.$bookingId.extend.tsx"),
    route("profile", "routes/profile.tsx"),
    route("referrals", "routes/referrals.tsx"),
    route("logout", "routes/logout.ts"),
    ...visualRoutes,
  ]),
  layout("routes/_auth.tsx", [
    route("auth", "routes/auth.tsx"),
    route("verify", "routes/verify.tsx"),
    route("fleet-owner/login", "routes/fleet-owner.login.tsx"),
    route("fleet-owner/verify", "routes/fleet-owner.verify.tsx"),
    route("admin/login", "routes/admin.login.tsx"),
    route("admin/verify", "routes/admin.verify.tsx"),
  ]),
  route("fleet-owner/logout", "routes/fleet-owner.logout.ts"),
  route("fleet-owner", "routes/fleet-owner.tsx", [
    layout("routes/fleet-owner.dashboard.tsx", [index("routes/fleet-owner._index.tsx")]),
    route("cars", "routes/fleet-owner.cars.tsx"),
    route("cars/:carId", "routes/fleet-owner.cars.$carId.tsx"),
    route("cars/:carId/edit", "routes/fleet-owner.cars.$carId.edit.tsx"),
    route("promotions", "routes/fleet-owner.promotions.tsx"),
    route("payout-transactions", "routes/fleet-owner.payout-transactions.tsx"),
  ]),
  route("admin/logout", "routes/admin.logout.ts"),
  route("admin", "routes/admin.tsx", [
    index("routes/admin._index.tsx"),
    route("cars", "routes/admin.cars.tsx"),
    route("cars/:carId", "routes/admin.cars.$carId.tsx"),
    route("documents/:documentId", "routes/admin.documents.$documentId.ts"),
    route("financials", "routes/admin.financials.tsx"),
    route("financials/refunds/:paymentId", "routes/admin.financials.refunds.$paymentId.tsx"),
    route(
      "financials/payouts/:payoutTransactionId",
      "routes/admin.financials.payouts.$payoutTransactionId.tsx",
    ),
    route("fees", "routes/admin.fees.tsx"),
    route("addon-rates", "routes/admin.addon-rates.tsx"),
  ]),
] satisfies RouteConfig;
